### PR TITLE
lost connection handling

### LINKED ISSUE #33: Client should gracefully handle server disconnect and vice versa

### PR DESCRIPTION
**Pull request by farnaf**
addressing this: https://github.com/ucsd-cse125-sp23/group-1/issues/33

any feedback would be appreciated!

### CODE REVIEW

**Comment by AW0723** [comment]
what's the expected behavior?

**Comment by farnaf** [comment]
> what's the expected behavior?

in current changes:

1. client programs are terminated when server disconnects
2. server is only terminated when *all* clients/players disconnect

**Review by jacksonconte — APPROVED** [review]
Looks good as an interim. When we add menu states we should probably send the player back to the main menu with an error box instead of panicking

**Review by AW0723 — APPROVED** [review]

**Review by katiehsieh — COMMENTED** [review]
It looks like the lost connection handling only works after starting the game on the server. For example, when I close all the clients before starting the game, the server still keeps running / waiting for more client connections. I'm not sure if this is something we also want to handle, or if it's not necessary since the game hasn't started yet.

**Pull request merged**
